// customer-angular/src/app/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.css'
})
export class DashboardComponent {
  get email(): string | null {
    return localStorage.getItem('email');
  }
}



<div class="dashboard">
  <!-- <header class="dashboard-header">
    <h2>Dashboard</h2>   
  </header> -->
  
  <main class="dashboard-content">
    <div class="dashboard-cards">

      <div class="card">
        <h3>Customers</h3>
        <p>View and manage customer information</p>
        <a routerLink="/customers" class="card-link">View Customers</a>
      </div>      
      <div class="card">
        <h3>Products</h3>
        <p>View and manage product information</p>
        <a routerLink="/products" class="card-link">View Products</a>
      </div>

       <div class="card">
        <h3>Customers</h3>
        <p>View and manage customer information</p>
        <a routerLink="/customers" class="card-link">View Customers</a>
      </div>      
      <div class="card">
        <h3>Products</h3>
        <p>View and manage product information</p>
        <a routerLink="/products" class="card-link">View Products</a>
      </div>

      <div class="card">
        <h3>Customers</h3>
        <p>View and manage customer information</p>
        <a routerLink="/customers" class="card-link">View Customers</a>
      </div>      
      <div class="card">
        <h3>Products</h3>
        <p>View and manage product information</p>
        <a routerLink="/products" class="card-link">View Products</a>
      </div>

    </div>
  </main>
</div>

// customer-react/src/components/dashboard/Dashboard.js
import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import './Dashboard.css';

export default function Dashboard() {
  const navigate = useNavigate();
  const email = localStorage.getItem('email');
  
  const handleLogout = () => {
    localStorage.removeItem('email');
    navigate('/login', { replace: true });
  };

  return (
    <div className="dashboard">
      {/* <header className="dashboard-header">
        <h2>Dashboard</h2>       
      </header> */}
      
      <main className="dashboard-content">
        <div className="dashboard-cards">

          <div className="card">
            <h3>Customers</h3>
            <p>View and manage customer information</p>
            <Link to="/customers" className="card-link">View Customers</Link>
          </div>
          
          <div className="card">
            <h3>Products</h3>
            <p>View and manage product information</p>
            <Link to="/products" className="card-link">View Products</Link>
          </div>

           <div className="card">
            <h3>Customers</h3>
            <p>View and manage customer information</p>
            <Link to="/customers" className="card-link">View Customers</Link>
          </div>
          
          <div className="card">
            <h3>Products</h3>
            <p>View and manage product information</p>
            <Link to="/products" className="card-link">View Products</Link>
          </div>

           <div className="card">
            <h3>Customers</h3>
            <p>View and manage customer information</p>
            <Link to="/customers" className="card-link">View Customers</Link>
          </div>
          
          <div className="card">
            <h3>Products</h3>
            <p>View and manage product information</p>
            <Link to="/products" className="card-link">View Products</Link>
          </div>         

        </div>
      </main>
    </div>
  );
}
