// customer-angular/src/app/login/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators, FormGroup } from '@angular/forms';
import { Router } from '@angular/router';
import { DataService } from '../../services/data.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  private readonly fb: FormBuilder = inject(FormBuilder);
  private readonly router: Router = inject(Router);
  private readonly dataService: DataService = inject(DataService);

  form: FormGroup = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]]
  }); 

  ngOnInit(): void {
    const email = localStorage.getItem('email');
    if (email && email.trim().length > 0) {
      this.dataService.updateIsLoggedIn(true);

      if (window.location.pathname.includes('/login'))
        this.router.navigate(['/dashboard']);       
    }
  }

  handleSubmit(): void {
    this.form.markAllAsTouched();
    if (this.form.invalid) {
      return;
    }

    const email = this.form.value.email as string;
    localStorage.setItem('email', email);
    this.dataService.updateIsLoggedIn(true);
    this.router.navigate(['/dashboard']);
  }
}



<div class="login-container">
  <h2>Login</h2>
  <form [formGroup]="form" (ngSubmit)="handleSubmit()">
    <div class="form-group">
      <label for="email">Email</label>
      <input id="email" type="email" formControlName="email" />
      <div class="error" *ngIf="form.get('email')?.touched && form.get('email')?.invalid">
        Please enter a valid email.
      </div>
    </div>

    <div class="form-group">
      <label for="password">Password</label>
      <input id="password" type="password" formControlName="password" />
      <div class="error" *ngIf="form.get('password')?.touched && form.get('password')?.invalid">
        Password must be at least 6 characters.
      </div>
    </div>

    <button type="submit">Continue</button>
  </form>
</div>

// customer-react/src/components/login/Login.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { dataService } from '../../services/dataService';
import './Login.css';

export default function Login() {
  const [formData, setFormData] = useState({
    email: '',
    password: ''
  });
  const [errors, setErrors] = useState({});
  const [touched, setTouched] = useState({});
  const navigate = useNavigate();

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
    
    // Clear error when user starts typing
    if (errors[name]) {
      setErrors(prev => ({
        ...prev,
        [name]: ''
      }));
    }
  };

  const handleBlur = (e) => {
    const { name } = e.target;
    setTouched(prev => ({
      ...prev,
      [name]: true
    }));
  };

  const validateForm = () => {
    const newErrors = {};

    if (!formData.email) {
      newErrors.email = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'Please enter a valid email';
    }

    if (!formData.password) {
      newErrors.password = 'Password is required';
    } else if (formData.password.length < 6) {
      newErrors.password = 'Password must be at least 6 characters';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    
    // Mark all fields as touched
    setTouched({
      email: true,
      password: true
    });

    if (validateForm()) {
      // Store email in localStorage (simulating login)
      localStorage.setItem('email', formData.email);
      dataService.updateIsLoggedIn(true);
      navigate('/dashboard');
    }
  };

  return (
    <div className="login-container">
      <h2>Login</h2>
      <form onSubmit={handleSubmit}>
        <div className="form-group">
          <label htmlFor="email">Email</label>
          <input
            id="email"
            type="email"
            name="email"
            value={formData.email}
            onChange={handleChange}
            onBlur={handleBlur}
          />
          {touched.email && errors.email && <div className="error">{errors.email}</div>}
        </div>

        <div className="form-group">
          <label htmlFor="password">Password</label>
          <input
            id="password"
            type="password"
            name="password"
            value={formData.password}
            onChange={handleChange}
            onBlur={handleBlur}
          />
          {touched.password && errors.password && <div className="error">{errors.password}</div>}
        </div>

        <button type="submit">Continue</button>
      </form>
    </div>
  );
}
