// customer-angular/src/app/header/header.component.ts
import { Component, inject, OnInit, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { DataService } from '../../services/data.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent implements OnInit {
  @Input() isSidenavCollapsed: boolean = false;
  private readonly router: Router = inject(Router);
  private readonly dataService: DataService = inject(DataService);
  private subscription!: Subscription;
  isLoggedIn = false;  
  userEmail: string = '';
  
  ngOnInit() {

     this.subscription = this.dataService.loggedIn$.subscribe(value => {
      this.userEmail = localStorage.getItem('email') || '';
      this.isLoggedIn = value;
    });

  }

  logout() {
    localStorage.removeItem('email');
    this.dataService.updateIsLoggedIn(false);
    this.router.navigate(['/login']);
  }
  
  ngOnDestroy() {
    // Prevent memory leaks
    this.subscription.unsubscribe();
  }
}

<header class="header" [class.sidenav-collapsed]="isSidenavCollapsed">
  <div class="header-content">
    <div class="logo-section">
      <div class="logo">
        <span class="logo-icon">🏢</span>
        <span class="logo-text">F Mart</span>
        <!-- <span class="logo-text">Customer Management System</span> -->
      </div>
    </div>
    
    <div class="user-section" *ngIf="isLoggedIn">
      <div class="user-info">
        <span class="user-icon">👤</span>
        <span class="user-email">{{ userEmail }}</span>
      </div>
      <button class="logout-btn" (click)="logout()">    
        <!-- <span class="logout-icon">🚪</span> -->
        Logout
      </button>
    </div>
  </div>
</header>

// customer-react/src/components/header/Header.js
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { dataService } from '../../services/dataService';
import './Header.css';

const Header = ({ isSidenavCollapsed }) => {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [userEmail, setUserEmail] = useState('');
  const navigate = useNavigate();

  useEffect(() => {
  
     const loggedInSubscription = dataService.loggedInSubject.subscribe((value) => {        
        setUserEmail(localStorage.getItem('email'));
        setIsLoggedIn(value);
      });

      return () => {
        loggedInSubscription.unsubscribe(); // Unsubscribe on unmount
      };

  }, []);

  const logout = () => {
    localStorage.removeItem('email');
    dataService.updateIsLoggedIn(false);
    navigate('/login');
  };

  return (
    <header className={`header`}>
      <div className="header-content">
        <div className="logo-section">
          <div className="logo">
            <span className="logo-icon">🏢</span>
            <span className="logo-text">F Mart</span>
          </div>
        </div>
        
        {isLoggedIn && (
          <div className="user-section">
            <div className="user-info">
              <span className="user-icon">👤</span>
              <span className="user-email">{userEmail}</span>
            </div>
            <button className="logout-btn" onClick={logout}>
              Logout
            </button>
          </div>
        )}
      </div>
    </header>
  );
};

export default Header;
