// customer-react/src/components/sidenav/Sidenav.js
import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import './Sidenav.css';

const Sidenav = ({ onCollapsedStateChanged }) => {
  const [userEmail, setUserEmail] = useState('');
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [navItems, setNavItems] = useState([]);
  const location = useLocation();
  const navigate = useNavigate();

  useEffect(() => {
    const email = localStorage.getItem('email');
    setUserEmail(email || '');

    if (email) {
      const items = [
        { icon: '📊', label: 'Dashboard', route: '/dashboard', isActive: false },
        { icon: '👥', label: 'Customers', route: '/customers', isActive: false },
        { icon: '📦', label: 'Products', route: '/products', isActive: false },
      ];
      setNavItems(items);
      updateActiveRoute(items);
    }
  }, []);

  useEffect(() => {
    if (navItems.length > 0) {
      updateActiveRoute(navItems);
    }
  }, [location.pathname]);

  const toggleCollapse = () => {
    const newCollapsedState = !isCollapsed;
    setIsCollapsed(newCollapsedState);
    onCollapsedStateChanged(newCollapsedState);
  };

  const updateActiveRoute = (items) => {
    const currentRoute = location.pathname;
    const updatedItems = items.map(item => ({
      ...item,
      isActive: currentRoute === item.route
    }));
    setNavItems(updatedItems);
  };

  const handleNavClick = (route) => {
    navigate(route);
  };

  return (
    <nav className={`sidenav ${isCollapsed ? 'collapsed' : ''}`}>
      <div className="sidenav-header">
        <button 
          className="toggle-btn" 
          onClick={toggleCollapse} 
          aria-label={isCollapsed ? 'Expand navigation' : 'Collapse navigation'}
        >
          <span className={`toggle-icon ${isCollapsed ? 'rotated' : ''}`}>☰</span>
        </button>
        {!isCollapsed && (
          <div className="nav-title">
            <span>Menu</span>
          </div>
        )}
      </div>

      <ul className="nav-list">
        {navItems.map((item, index) => (
          <li key={index} className="nav-item">
            <a 
              className={`nav-link ${item.isActive ? 'active' : ''}`}
              href="#"
              onClick={(e) => {
                e.preventDefault();
                handleNavClick(item.route);
              }}
              title={isCollapsed ? item.label : ''}
            >
              <span className="nav-icon">{item.icon}</span>
              {!isCollapsed && <span className="nav-label">{item.label}</span>}
            </a>
          </li>
        ))}
      </ul>

      {!isCollapsed && (
        <div className="sidenav-footer">
          <div className="footer-info">
            <small>F Mart v1.0</small>
          </div>
        </div>
      )}
    </nav>
  );
};

export default Sidenav;

// customer-angular/src/app/sidenav/sidenav.component.ts
import { Component, inject, OnInit, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { DataService } from '../../services/data.service';

interface NavItem {
  icon: string;
  label: string;
  route: string;
  isActive: boolean;
}

@Component({
  selector: 'app-sidenav',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './sidenav.component.html',
  styleUrl: './sidenav.component.css'
})
export class SidenavComponent implements OnInit {
  @Output() collapsedStateChanged = new EventEmitter<boolean>();
  private readonly dataService: DataService = inject(DataService);
  // async pipe subscribes automatically
  //isLoggedIn$ = this.dataService.loggedIn$;  
  isCollapsed = false;
  
  navItems: NavItem[] = [];
   
  constructor(private router: Router) {}

  ngOnInit() {
        
    if(this.dataService.isLoggedIn){
      this.navItems = [
        { icon: '📊', label: 'Dashboard', route: '/dashboard', isActive: false },
        { icon: '👥', label: 'Customers', route: '/customers', isActive: false },
        { icon: '📦', label: 'Products', route: '/products', isActive: false },
        //{ icon: '➕', label: 'Add Customer', route: '/customer/add', isActive: false },
      ];

      this.updateActiveRoute();
      this.router.events.subscribe(() => {
        this.updateActiveRoute();
      });
    }
    
  }

  toggleCollapse() {
    this.isCollapsed = !this.isCollapsed;
    this.collapsedStateChanged.emit(this.isCollapsed);
  }

  private updateActiveRoute() {
    const currentRoute = this.router.url;
    this.navItems.forEach(item => {
      item.isActive = currentRoute === item.route;
    });
  }
}

<nav class="sidenav" [class.collapsed]="isCollapsed">
  <div class="sidenav-header">
    <button class="toggle-btn" (click)="toggleCollapse()" [attr.aria-label]="isCollapsed ? 'Expand navigation' : 'Collapse navigation'">
      <span class="toggle-icon" [class.rotated]="isCollapsed">☰</span>
    </button>
    <div class="nav-title" *ngIf="!isCollapsed">
      <span>Menu</span>
    </div>
  </div>

  <ul class="nav-list">
    <li class="nav-item" *ngFor="let item of navItems">
      <a 
        class="nav-link" 
        [routerLink]="item.route"
        [class.active]="item.isActive"
        [attr.title]="isCollapsed ? item.label : ''"
      >
        <span class="nav-icon">{{ item.icon }}</span>
        <span class="nav-label" *ngIf="!isCollapsed">{{ item.label }}</span>
      </a>
    </li>
  </ul>

  <div class="sidenav-footer" *ngIf="!isCollapsed">
    <div class="footer-info">
      <small>F Mart v1.0</small>
    </div>
  </div>
</nav>
